(function(){
'use strict';
const hero=document.querySelector('.hero'),pic=hero&&hero.querySelector(':scope > img'),area=document.querySelector('.choiceArea');
if(!hero||!pic||!area)return;
const pool=document.querySelector('.waterTint'),tile=document.querySelector('.tileOverlay'),deck=document.querySelector('.deckOverlay');
if(!pool||!tile||!deck)return;
const DEMO={pool:[[8,55],[22,49],[50,48],[78,45],[96,63],[91,91],[58,96],[25,92],[7,75]],tile:[[10,51],[25,47],[51,46],[78,43],[97,60],[96,65],[78,49],[51,52],[25,53],[10,57]],deck:[[0,57],[11,51],[24,57],[39,70],[100,57],[100,100],[0,100]]};
const masks={pool:DEMO.pool.map(p=>p.slice()),tile:DEMO.tile.map(p=>p.slice()),deck:DEMO.deck.map(p=>p.slice())};
let editType=null,points=[],queue=[],scale=1,tx=0,ty=0,drag=false,lastX=0,lastY=0;
function clip(a){return 'polygon('+a.map(p=>p[0].toFixed(2)+'% '+p[1].toFixed(2)+'%').join(',')+')'}
function applyMasks(){pool.style.clipPath=clip(masks.pool);tile.style.clipPath=clip(masks.tile);deck.style.clipPath=clip(masks.deck)}
function resetMasks(){Object.keys(DEMO).forEach(k=>masks[k]=DEMO[k].map(p=>p.slice()));applyMasks()}
function labelText(name){const x=document.querySelector('input[name="'+name+'"]:checked');const l=x&&document.querySelector('label[for="'+x.id+'"]');const b=l&&l.querySelector('b');return b?b.textContent.trim():'Not selected'}
function syncSelected(){document.querySelectorAll('label.card').forEach(l=>l.classList.remove('liv-selected'));['finish','tile','deck','yard'].forEach(n=>{const x=document.querySelector('input[name="'+n+'"]:checked');const l=x&&document.querySelector('label[for="'+x.id+'"]');if(l)l.classList.add('liv-selected')})}
const tools=document.createElement('div');tools.className='photoTools';tools.innerHTML='<strong>Instant visualizer — no API credits</strong><small>Selections update directly in your browser. Upload any pool photo, then outline the pool, waterline and deck once so the materials stay in the exact areas you choose.</small><div class="toolRow"><label class="uploadBtn" for="poolPhoto">UPLOAD POOL PHOTO</label><input id="poolPhoto" type="file" accept="image/*" hidden><button class="secondaryBtn" id="demoPhoto" type="button">USE DEMO PHOTO</button><button class="secondaryBtn" id="markAreas" type="button">MARK AREAS</button></div><div class="selectionState ok" id="selectionState">Demo photo ready. Tap any material to preview it instantly.</div>';
area.prepend(tools);
const input=tools.querySelector('#poolPhoto'),state=tools.querySelector('#selectionState');
function setState(t,c=''){state.className='selectionState'+(c?' '+c:'');state.textContent=t}
input.addEventListener('change',()=>{const f=input.files&&input.files[0];if(!f)return;if(!f.type.startsWith('image/'))return setState('Please choose a JPG, PNG or other image file.','error');pic.src=URL.createObjectURL(f);pool.style.opacity='0';tile.style.opacity='0';deck.style.opacity='0';resetView();setState('Photo loaded. Tap MARK AREAS and outline the pool, waterline and deck.','warn')});
tools.querySelector('#demoPhoto').onclick=()=>{pic.src='/hero.jpg?v=free2';resetMasks();pool.style.opacity='';tile.style.opacity='';deck.style.opacity='';resetView();setState('Demo photo restored. Material changes are instant and free.','ok')};
tools.querySelector('#markAreas').onclick=()=>{queue=['tile','deck'];startEdit('pool')};
const editor=document.createElement('div');editor.className='surfaceEditor';editor.innerHTML='<div class="editPoints"></div><div class="editPanel"><b id="editTitle">Mark area</b><span>Tap around the exact surface. Use 4–12 points, then tap Done.</span><div><button id="undoPoint">UNDO</button><button id="clearPoints">CLEAR</button><button id="donePoints" class="done">DONE</button></div></div>';hero.appendChild(editor);const pointLayer=editor.querySelector('.editPoints');
function drawPoints(){pointLayer.innerHTML='';points.forEach(p=>{const d=document.createElement('i');d.style.left=p[0]+'%';d.style.top=p[1]+'%';pointLayer.appendChild(d)})}
function startEdit(type){resetView();editType=type;points=[];hero.classList.add('editingSurface');editor.querySelector('#editTitle').textContent='Mark '+({pool:'pool interior',tile:'waterline tile band',deck:'deck / coping'}[type]);drawPoints();setState('Tap around the '+type+' surface, then tap Done.','warn')}
pointLayer.addEventListener('pointerdown',e=>{if(!editType)return;const r=pointLayer.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;if(x>=0&&x<=100&&y>=0&&y<=100){points.push([x,y]);drawPoints()}});
editor.querySelector('#undoPoint').onclick=()=>{points.pop();drawPoints()};editor.querySelector('#clearPoints').onclick=()=>{points=[];drawPoints()};editor.querySelector('#donePoints').onclick=()=>{if(points.length<3)return setState('Add at least 3 points before finishing.','warn');masks[editType]=points.map(p=>p.slice());applyMasks();if(editType==='pool')pool.style.opacity='';if(editType==='tile')tile.style.opacity='';if(editType==='deck')deck.style.opacity='';hero.classList.remove('editingSurface');editType=null;points=[];drawPoints();setState('Area saved. The material will stay inside the surface you marked.','ok');if(queue.length)setTimeout(()=>startEdit(queue.shift()),180)};
function addEditButtons(){[['.p1','pool','EDIT POOL AREA'],['.p2','tile','EDIT WATERLINE AREA'],['.p3','deck','EDIT DECK AREA']].forEach(([sel,type,text])=>{const p=document.querySelector(sel);if(!p)return;const b=document.createElement('button');b.type='button';b.className='areaEditBtn';b.textContent=text;b.onclick=()=>startEdit(type);p.appendChild(b)})}
function addFineTune(){const box=document.createElement('div');box.className='fineTune';box.innerHTML='<b>Fine tune preview</b><label>Pool finish strength <input id="poolOpacity" type="range" min="0" max="70" value="29"><output>29%</output></label><label>Waterline opacity <input id="tileOpacity" type="range" min="20" max="100" value="85"><output>85%</output></label><label>Tile scale <input id="tileScale" type="range" min="25" max="140" value="44"><output>44px</output></label><label>Deck opacity <input id="deckOpacity" type="range" min="15" max="90" value="50"><output>50%</output></label><label>Paver scale <input id="deckScale" type="range" min="80" max="320" value="190"><output>190px</output></label>';area.appendChild(box);function bind(id,el,mode){const r=box.querySelector('#'+id),o=r.parentElement.querySelector('output');const go=()=>{if(mode==='opacity')el.style.opacity=(+r.value/100);else el.style.backgroundSize=r.value+'px auto';o.textContent=r.value+(mode==='opacity'?'%':'px')};r.oninput=go;go()}bind('poolOpacity',pool,'opacity');bind('tileOpacity',tile,'opacity');bind('tileScale',tile,'size');bind('deckOpacity',deck,'opacity');bind('deckScale',deck,'size')}
function addCustomFinish(){const p=document.querySelector('.p1');if(!p)return;const box=document.createElement('div');box.className='customFinish';box.innerHTML='<b>Do not see your plaster option?</b><span>Add it manually with no AI or API charge.</span><div><input id="customFinishName" placeholder="Finish name"><input id="customFinishColor" type="color" value="#4d94ae"><button type="button">ADD FINISH</button></div><div id="customFinishResult"></div>';const cont=p.querySelector('.continue');p.insertBefore(box,cont||null);box.querySelector('button').onclick=()=>{const name=box.querySelector('#customFinishName').value.trim();if(!name)return;let radio=document.querySelector('#customFinishFree');if(!radio){radio=document.createElement('input');radio.type='radio';radio.name='finish';radio.id='customFinishFree';document.body.appendChild(radio)}const result=box.querySelector('#customFinishResult');result.innerHTML='<label class="card liv-selected" for="customFinishFree"><div class="sw customSw"></div><b></b><span>Custom pool finish</span></label>';result.querySelector('b').textContent=name;const color=box.querySelector('#customFinishColor').value;result.querySelector('.customSw').style.background='linear-gradient(135deg,'+color+',#e7ecea)';radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}));pool.style.background=color;setState(name+' added. Preview updated instantly.','ok')}}
function applyView(){pic.style.transform='translate3d('+tx+'px,'+ty+'px,0) scale('+scale+')';pool.style.transform='translate3d('+tx+'px,'+ty+'px,0) scale('+scale+')';tile.style.transform='translate3d('+tx+'px,'+ty+'px,0) scale('+scale+')';deck.style.transform='translate3d('+tx+'px,'+ty+'px,0) scale('+scale+')'}function resetView(){scale=1;tx=0;ty=0;applyView()}function zoomBy(f){scale=Math.max(1,Math.min(4,scale*f));if(scale===1){tx=0;ty=0}applyView()}
const zoom=document.createElement('div');zoom.className='zoomTools';zoom.innerHTML='<button type="button">+</button><button type="button">−</button><button type="button" class="resetZoom">1:1</button>';hero.appendChild(zoom);const zb=zoom.querySelectorAll('button');zb[0].onclick=e=>{e.stopPropagation();zoomBy(1.25)};zb[1].onclick=e=>{e.stopPropagation();zoomBy(.8)};zb[2].onclick=e=>{e.stopPropagation();resetView()};hero.addEventListener('wheel',e=>{if(hero.classList.contains('editingSurface'))return;e.preventDefault();zoomBy(e.deltaY<0?1.12:.89)},{passive:false});hero.addEventListener('pointerdown',e=>{if(hero.classList.contains('editingSurface')||e.target.closest('.zoomTools')||scale<=1)return;drag=true;lastX=e.clientX;lastY=e.clientY;hero.setPointerCapture(e.pointerId)});hero.addEventListener('pointermove',e=>{if(!drag)return;tx+=e.clientX-lastX;ty+=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;applyView()});hero.addEventListener('pointerup',()=>drag=false);hero.addEventListener('pointercancel',()=>drag=false);
function updateEstimate(){const sels=document.querySelectorAll('details.dims select');if(sels.length<2)return;const l=parseFloat(sels[0].value)||24,w=parseFloat(sels[1].value)||12;let deckW=document.querySelector('#freeDeckWidth');if(!deckW){const grid=document.querySelector('.dimgrid');if(grid){const lab=document.createElement('label');lab.textContent='Deck width';deckW=document.createElement('select');deckW.id='freeDeckWidth';deckW.innerHTML='<option>3 ft</option><option selected>4 ft</option><option>5 ft</option><option>6 ft</option>';lab.appendChild(deckW);grid.appendChild(lab);deckW.onchange=updateEstimate}}const d=parseFloat(deckW&&deckW.value)||4,per=2*(l+w),tileSq=Math.ceil(per*.5*1.1),deckSq=Math.ceil(((l+2*d)*(w+2*d)-l*w)*1.1);const vals=document.querySelectorAll('.estimate .row b');if(vals[0])vals[0].textContent='~'+tileSq+' sq ft incl. waste';if(vals[1])vals[1].textContent='~'+deckSq+' sq ft incl. waste';if(vals[2])vals[2].textContent='~'+Math.ceil(per)+' ln ft'}document.querySelectorAll('details.dims select').forEach(s=>s.addEventListener('change',updateEstimate));
document.addEventListener('change',e=>{if(e.target&&['finish','tile','deck','yard'].includes(e.target.name)){syncSelected();setState(labelText(e.target.name)+' selected. Preview updated instantly.','ok')}});
const legal=document.createElement('div');legal.className='legalDisclaimer';legal.textContent='Visualizer disclaimer: previews are approximations for design inspiration. Actual material color, texture, scale, water color, lighting and installed appearance can differ, and screens display color differently. Verify current product specifications and physical samples before ordering or installation.';area.appendChild(legal);
addEditButtons();addFineTune();addCustomFinish();resetMasks();syncSelected();updateEstimate();
})();