const http=require('http'),fs=require('fs'),path=require('path'),OpenAI=require('openai');const {toFile}=require('openai/uploads');const port=process.env.PORT||3000,MAX=24*1024*1024;
const BASE='https://images.unsplash.com/photo-1665110654191-e68f223f449d?auto=format&fit=crop&fm=jpg&q=82&w=1800';
function send(res,s,o){res.writeHead(s,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(o))}
function body(req){return new Promise((ok,no)=>{let n=0,a=[];req.on('data',c=>{n+=c.length;if(n>MAX){no(Error('Request too large'));req.destroy()}else a.push(c)});req.on('end',()=>{try{ok(JSON.parse(Buffer.concat(a).toString()||'{}'))}catch(e){no(e)}});req.on('error',no)})}
async function fileFromUrl(url,name){if(!url)return null;const r=await fetch(url);if(!r.ok)throw Error('Could not load '+name);const type=(r.headers.get('content-type')||'image/jpeg').split(';')[0];return toFile(Buffer.from(await r.arrayBuffer()),name,{type})}
async function render(b){if(!process.env.OPENAI_API_KEY)throw Error('AI renderer is not configured');const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const imgs=[await fileFromUrl(BASE,'pool-composition.jpg')];if(b.tileImage)imgs.push(await fileFromUrl(b.tileImage,'selected-waterline-tile.jpg'));if(b.deckImage)imgs.push(await fileFromUrl(b.deckImage,'selected-deck.jpg'));
const prompt=`Create a photorealistic private Las Vegas/Henderson backyard pool visualization that strongly follows image 1 for composition, camera height and overall pool-forward framing.
COMPOSITION: the swimming pool must dominate the foreground and middle of the frame, like a customer standing at the rear patio looking outward across the pool. Show lots of water and deck, not a doorway, hallway or house facade. A small edge of stucco house/patio may appear only along the far RIGHT edge. Across the back of the yard use a normal 6-foot tan/gray CMU block privacy wall with modest desert landscaping. Optional distant mountains are fine. Include a realistic raised spa or small raised bond-beam/water-feature area only if it fits naturally. No people.
ABSOLUTELY AVOID: commercial pool, hotel/resort look, apartment complex, glass fencing, lane lines, signage, giant tropical landscaping, floating materials, vertical deck texture, tile bands in the sky/walls, or changing the whole architecture.
MATERIALS: pool interior/plaster finish = ${b.finish||'selected finish'}. Waterline tile = ${b.tile||'selected tile'}. Deck/pavers = ${b.deck||'selected deck'}. Yard direction = ${b.yard||'simple Las Vegas residential desert yard'}.
REFERENCE IMAGES: image 2, if present, is the EXACT selected waterline tile product. Apply it ONLY to the narrow 6-inch-ish waterline band around the inside perimeter of the pool and spa, following perspective and scale. Image 3, if present, is the EXACT selected deck/paver product. Apply it ONLY to horizontal pool-deck/hardscape surfaces at realistic paver scale. Never apply tile or paver imagery to walls, sky, water, plants, furniture, or house surfaces.
PLASTER: visibly change the pool interior/water tone to match the selected finish while keeping realistic water depth, reflections, ripples and caustics.
Keep material boundaries clean, construction-realistic and believable.`;
const out=await client.images.edit({model:'gpt-image-2',image:imgs,prompt,size:'1536x1024',quality:'high',input_fidelity:'high'});const x=out.data&&out.data[0];if(!x)throw Error('Renderer returned no image');return x.b64_json?'data:image/png;base64,'+x.b64_json:x.url}
function loadUI(){let h=fs.readdirSync(path.join(__dirname,'ui-live')).filter(x=>x.endsWith('.txt')).sort().map(x=>fs.readFileSync(path.join(__dirname,'ui-live',x),'utf8')).join('');h=h.replace(/https:\/\/images\.unsplash\.com\/photo-[^\"']+/,BASE);h=h.replace('</body>',`<style>.waterTint,.tileOverlay,.deckOverlay{display:none!important}.hero>img{object-position:center center}.renderBtn{display:block;width:100%;border:0;border-radius:10px;padding:14px;background:#102628;color:#fff;font-weight:800;margin:14px 0;cursor:pointer}.renderMsg{font-size:12px;color:#687171;margin:8px 0 18px}.hero.rendering:after{content:'Creating realistic pool preview…';position:absolute;inset:0;background:rgba(0,0,0,.52);color:#fff;display:grid;place-items:center;font:800 16px Arial;z-index:15}.heroCopy p{max-width:290px}</style><script>(function(){const hero=document.querySelector('.hero'),pic=hero.querySelector('img');const btn=document.createElement('button');btn.className='renderBtn';btn.textContent='RENDER MY SELECTIONS';const msg=document.createElement('div');msg.className='renderMsg';msg.textContent='Choose finish, tile, deck and yard, then create the realistic pool preview.';document.querySelector('.choiceArea').append(btn,msg);function sel(n){return document.querySelector('input[name="'+n+'"]:checked')}function lab(n){const x=sel(n);return x?document.querySelector('label[for="'+x.id+'"]'):null}function text(n){const l=lab(n);return l?l.innerText.replace(/\\n/g,' ').trim():''}function image(n){const l=lab(n);const im=l&&l.querySelector('img');return im?im.src:''}btn.onclick=async()=>{hero.classList.add('rendering');btn.disabled=true;msg.textContent='Applying your materials to the pool, waterline, deck and yard…';try{const r=await fetch('/api/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({finish:text('finish'),tile:text('tile'),tileImage:image('tile'),deck:text('deck'),deckImage:image('deck'),yard:text('yard')})});const j=await r.json();if(!r.ok)throw Error(j.error||'Render failed');pic.src=j.image;msg.textContent='Rendered. Change a selection and render again to compare.'}catch(e){msg.textContent='Render failed: '+e.message}finally{hero.classList.remove('rendering');btn.disabled=false}}})();</script></body>`);return h}
let UI;try{UI=loadUI()}catch(e){console.error(e);UI='<!doctype html><h1>LIV Visualizer temporarily unavailable</h1>'}
http.createServer(async(req,res)=>{const p=(req.url||'/').split('?')[0];if(p==='/api/render'&&req.method==='POST'){try{return send(res,200,{image:await render(await body(req))})}catch(e){console.error(e);return send(res,500,{error:e.message})}}if(p==='/'||p==='/index.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate'});return res.end(UI)}res.writeHead(404);res.end('Not found')}).listen(port,'0.0.0.0',()=>console.log('LIV material visualizer on '+port));